package game::server::Model::main;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'game::server::Model::schemas::main',
    
    connect_info => {
        dsn => 'dbi:Pg:host=localhost;dbname=game_serve;port=5432',
        user => 'game_serve',
        password => 'game_serve',
    }
);

=head1 NAME

game::server::Model::main - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<game::server>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<game::server::Model::schemas::main>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.49

=head1 AUTHOR

Paul Salcido

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
